name: Update GitHub Stats

# Trigger: run manually or every hour
on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repo
      - uses: actions/checkout@v3

      # Step 2: Replace placeholder with secret token
      - name: Replace token in README
        run: |
          sed -i "s|TOKEN_PLACEHOLDER|${{ secrets.GH_TOKEN }}|" README.md

      # Step 3: Commit and push changes
      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update GitHub stats" || echo "No changes to commit"
          git push
